CREATE TABLE schedule (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    passwd VARCHAR(255) NOT NULL,
    todo VARCHAR(300) NOT NULL,
    createdDateTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedDateTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);